# Executable name
NAME = ft_display_file

# Compile and flags
CC = cc
CFLAGS = -Wall -Wextra -Werror

# Source and header files
SRCS = *.c
HEADERS = *.h

# Removal command and flags
RM = rm
RMFLAGS = -rf -R

# Executable files
OBJS = *.o

# Compilation command
all: 
	$(CC) $(CFLAGS) $(SRCS) -o $(NAME)

# Removes executable file
clean:
	$(RM) $(RMFLAGS) $(name)

# Rebuilds the executable file
fclean: clean all